#include "FallDetect.h"
#include <iostream>

int main()
{
	string linkVideo = "";
	cout << "Type the link of video used to calculate human area:\n";
	getline(cin, linkVideo);
	VideoCapture cap(linkVideo);
	if (!cap.isOpened())
	{
		return -1;
	}
	Mat binaryImg;								// foreground mask fg mask generated by MOG2 method
	Mat frame;									// current frame
	Mat mhiDst;									// mhi image;

	// Detect fall- unconditional loop
	while (true) {
		cout << (double)clock() / CLOCKS_PER_SEC << endl;
		// Read Image;
		cap >> frame;
		if (frame.empty())
		{
			break;
		}
		//if (!CurlUtils::curlImg("http://192.168.0.222:8888/snapshot.cgi?&loginuse=admin&loginpas=admin", frame))
		//{
		//	continue;
		//}
		// Pre procesing- Resize
		resize(frame, frame, Size(FRAME_WIDTH, FRAME_HEIGHT));
		if (FallDetect::fallDetect2(frame, mhiDst, binaryImg))
		{
			cout << "\a" << endl;
		}

		//Display
		imshow("Shadow_Removed", binaryImg);
		imshow("Blur_Resize", frame);
		imshow("MHI", mhiDst);

		if (waitKey(5) >= 0)
			break;
	}
}